version: 2

jobs:
  build:
    docker:
      - image: node:8-stretch
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y xvfb # xvfb for running headless tests (headless X11 server).
      - run: apt-get install -y libgirepository1.0-dev libgtk-3-dev libgtkmm-3.0-dev libsigc++-2.0-dev # system dependencies for gtk-node
      - run: npm install
      - run: npm run build
      - run: xvfb-run -a npm test
